apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sed-ai-agent
spec:
  template:
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 8080
