apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sed-ai-web
spec:
  template:
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/WEB_IMAGE:TAG
          ports:
            - containerPort: 8080
